# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Year[0]
tagline:          'a place full of things'
description:      'Things that are, and are for your consideration.'
url:              http://panzerama.github.io
baseurl:          /

author:
  name:           'JD Panzer'
  url:            https://twitter.com/panzerama

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/panzerama/panzerama.github.io
