# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Year0
tagline:          'a place full of things'
description:      'These are not essays. These are not thoughts or musings or reflections or even very humble opinions. They just are, for your consideration.'
url:              http://panzerama.github.io
baseurl:          /

author:
  name:           'JD Panzer'
  url:            https://twitter.com/panzerama

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/panzerama/panzerama.github.io
